apiVersion: v1
kind: Namespace
metadata:
  name: desafio-api
  labels:
    app.kubernetes.io/part-of: kubernetes-challenge
---
apiVersion: v1
kind: Namespace
metadata:
  name: desafio-db
  labels:
    app.kubernetes.io/part-of: kubernetes-challenge
